version: '3'
 
services:
  mysql:
    image: mysql
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PW
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge